services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    volumes:
      - apache_data:/var/www/html
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: h
    networks:
      - my-app


  mariadb:
    image: mariadb:11.4
    ports:
      - "8082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: h
      MYSQL_DATABASE: database
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my-app

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    networks:
      - my-app

volumes:
  mariadb_data:
  apache_data:

networks:
  my-app:
