version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    volumes:
      - apache_data:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mariadb_data:
  apache_data:
